set_property PACKAGE_PIN Y1 [get_ports a]
set_property PACKAGE_PIN W3 [get_ports b]
set_property PACKAGE_PIN L4 [get_ports q]
set_property PACKAGE_PIN M4 [get_ports w]
set_property PACKAGE_PIN Y1 [get_ports x]
set_property PACKAGE_PIN W3 [get_ports y]
set_property PACKAGE_PIN U2 [get_ports z]
set_property IOSTANDARD LVCMOS33 [get_ports z]
set_property IOSTANDARD LVCMOS33 [get_ports y]
set_property IOSTANDARD LVCMOS33 [get_ports x]
set_property IOSTANDARD LVCMOS33 [get_ports w]
set_property IOSTANDARD LVCMOS33 [get_ports q]
set_property IOSTANDARD LVCMOS33 [get_ports b]
set_property IOSTANDARD LVCMOS33 [get_ports a]

set_property PACKAGE_PIN L4 [get_ports c]
set_property PACKAGE_PIN M4 [get_ports s]
set_property IOSTANDARD LVCMOS33 [get_ports c]
set_property IOSTANDARD LVCMOS33 [get_ports s]

