@echo off
REM ****************************************************************************
REM Vivado (TM) v2022.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Sat Oct 12 13:07:40 +0900 2024
REM SW Build 3526262 on Mon Apr 18 15:48:16 MDT 2022
REM
REM IP Build 3524634 on Mon Apr 18 20:55:01 MDT 2022
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim logic_gate_two_tb_behav -key {Behavioral:sim_1:Functional:logic_gate_two_tb} -tclbatch logic_gate_two_tb.tcl -view E:/vivado/week7/project_1/logic_gate_one_tb_behav.wcfg -log simulate.log"
call xsim  logic_gate_two_tb_behav -key {Behavioral:sim_1:Functional:logic_gate_two_tb} -tclbatch logic_gate_two_tb.tcl -view E:/vivado/week7/project_1/logic_gate_one_tb_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
