set_property PACKAGE_PIN Y1 [get_ports S0]
set_property PACKAGE_PIN W3 [get_ports S1]
set_property PACKAGE_PIN U2 [get_ports S2]
set_property IOSTANDARD LVCMOS33 [get_ports S0]
set_property IOSTANDARD LVCMOS33 [get_ports S1]
set_property IOSTANDARD LVCMOS33 [get_ports S2]
set_property PACKAGE_PIN L4 [get_ports {Y[0]}]
set_property PACKAGE_PIN M4 [get_ports {Y[1]}]
set_property PACKAGE_PIN M2 [get_ports {Y[2]}]
set_property PACKAGE_PIN N7 [get_ports {Y[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Y[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Y[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Y[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Y[0]}]

