set_property PACKAGE_PIN L4 [get_ports {out[0]}]
set_property PACKAGE_PIN M4 [get_ports {out[1]}]
set_property PACKAGE_PIN M2 [get_ports {out[2]}]
set_property PACKAGE_PIN N7 [get_ports {out[3]}]
set_property PACKAGE_PIN M7 [get_ports {out[4]}]
set_property PACKAGE_PIN M3 [get_ports {out[5]}]
set_property PACKAGE_PIN M1 [get_ports {out[6]}]
set_property PACKAGE_PIN N5 [get_ports {out[7]}]
set_property PACKAGE_PIN Y1 [get_ports {in[0]}]
set_property PACKAGE_PIN W3 [get_ports {in[1]}]
set_property PACKAGE_PIN U2 [get_ports {in[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {in[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {in[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {in[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out[0]}]


